[theme]
# Primary accent color for interactive elements.
primaryColor = "#00A2E8"

# Background color for the main content area.
backgroundColor = "#fff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "##f6f0f2"

# Color used for almost all text.
textColor = "#000"

[client]
toolbarMode = "minimal"